/**
 * @file    mpu6050.h
 * @brief   Driver cho cảm biến MPU6050 (Accelerometer + Gyroscope).
 *
 * Giao tiếp:  I2C3  (PA8=SCL, PC11=SDA)
 * Interrupt:  PA15  (EXTI15, Active-High, Data-Ready)
 *
 * Chức năng chính:
 *  - Khởi tạo cảm biến và kiểm tra kết nối (WHO_AM_I)
 *  - Đọc dữ liệu thô Accel + Gyro (6 trục)
 *  - Áp dụng Complementary Filter tính góc Pitch và Roll
 *  - Cung cấp callback ngắt Data-Ready (khi dùng interrupt PA15)
 */

#ifndef __MPU6050_H__
#define __MPU6050_H__

#ifdef __cplusplus
extern "C" {
#endif

/* Includes ------------------------------------------------------------------*/
#include "main.h"
#include "i2c.h"

/* ============================================================================
 *  HARDWARE CONFIGURATION
 * ============================================================================ */

/** Địa chỉ I2C 7-bit của MPU6050.
 *  AD0 nối GND  → 0x68 (mặc định)
 *  AD0 nối VCC  → 0x69                                                      */
#define MPU6050_I2C_ADDR        (0x68 << 1)   /* HAL dùng địa chỉ 8-bit       */

/** Handle I2C được dùng (generated by CubeMX) */
#define MPU6050_I2C_HANDLE      hi2c3

/** Timeout cho mọi thao tác I2C (ms) */
#define MPU6050_I2C_TIMEOUT_MS  10U

/** I2C3 Pins: PA8=SCL (AF2), PC11=SDA (AF8) – cấu hình trong i2c.c */

/** Chân Interrupt – PA15 (EXTI15) */
#define MPU6050_INT_PORT        GPIOA
#define MPU6050_INT_PIN         GPIO_PIN_15

/* ============================================================================
 *  THANH GHI MPU6050 (Register Map – trích từ datasheet RM-MPU-6000A)
 * ============================================================================ */
#define MPU6050_REG_SELF_TEST_X     0x0D
#define MPU6050_REG_SELF_TEST_Y     0x0E
#define MPU6050_REG_SELF_TEST_Z     0x0F
#define MPU6050_REG_SELF_TEST_A     0x10
#define MPU6050_REG_SMPLRT_DIV      0x19  /* Sample Rate Divider              */
#define MPU6050_REG_CONFIG          0x1A  /* DLPF config                      */
#define MPU6050_REG_GYRO_CONFIG     0x1B  /* Gyroscope full-scale range       */
#define MPU6050_REG_ACCEL_CONFIG    0x1C  /* Accelerometer full-scale range   */
#define MPU6050_REG_FIFO_EN         0x23
#define MPU6050_REG_INT_PIN_CFG     0x37  /* INT/DRDY pin config              */
#define MPU6050_REG_INT_ENABLE      0x38  /* Interrupt enable                 */
#define MPU6050_REG_INT_STATUS      0x3A  /* Interrupt status                 */
#define MPU6050_REG_ACCEL_XOUT_H    0x3B  /* Accel X high byte (đọc 14 byte) */
#define MPU6050_REG_TEMP_OUT_H      0x41  /* Temperature high byte            */
#define MPU6050_REG_GYRO_XOUT_H     0x43  /* Gyro X high byte                 */
#define MPU6050_REG_USER_CTRL       0x6A
#define MPU6050_REG_PWR_MGMT_1      0x6B  /* Power Management 1               */
#define MPU6050_REG_PWR_MGMT_2      0x6C  /* Power Management 2               */
#define MPU6050_REG_WHO_AM_I        0x75  /* Device identity = 0x68           */

/* ============================================================================
 *  HẰNG SỐ CẤU HÌNH
 * ============================================================================ */

/** Giá trị WHO_AM_I mong đợi từ MPU6050 */
#define MPU6050_WHOAMI_VALUE        0x68U

/** Bit DATA_RDY_EN trong INT_ENABLE */
#define MPU6050_INT_ENABLE_DATA_RDY 0x01U
/** Bit INT_LEVEL (active-low) và LATCH_INT_EN trong INT_PIN_CFG */
#define MPU6050_INTCFG_ACTIVE_HIGH  0x00U
#define MPU6050_INTCFG_ACTIVE_LOW   0x80U
#define MPU6050_INTCFG_LATCH_EN     0x20U
#define MPU6050_INTCFG_RD_CLEAR     0x10U

/* ============================================================================
 *  ENUM CẤU HÌNH DẢI ĐO
 * ============================================================================ */

/**
 * @brief  Dải đo của Gyroscope (FS_SEL bits[4:3] trong GYRO_CONFIG).
 */
typedef enum {
    MPU6050_GYRO_FS_250DPS  = 0x00,  /*!< ±250  °/s  – sensitivity 131.0 LSB/°/s  */
    MPU6050_GYRO_FS_500DPS  = 0x08,  /*!< ±500  °/s  – sensitivity  65.5 LSB/°/s  */
    MPU6050_GYRO_FS_1000DPS = 0x10,  /*!< ±1000 °/s  – sensitivity  32.8 LSB/°/s  */
    MPU6050_GYRO_FS_2000DPS = 0x18,  /*!< ±2000 °/s  – sensitivity  16.4 LSB/°/s  */
} MPU6050_GyroFS_t;

/**
 * @brief  Dải đo của Accelerometer (AFS_SEL bits[4:3] trong ACCEL_CONFIG).
 */
typedef enum {
    MPU6050_ACCEL_FS_2G  = 0x00,  /*!< ±2g   – sensitivity 16384 LSB/g */
    MPU6050_ACCEL_FS_4G  = 0x08,  /*!< ±4g   – sensitivity  8192 LSB/g */
    MPU6050_ACCEL_FS_8G  = 0x10,  /*!< ±8g   – sensitivity  4096 LSB/g */
    MPU6050_ACCEL_FS_16G = 0x18,  /*!< ±16g  – sensitivity  2048 LSB/g */
} MPU6050_AccelFS_t;

/**
 * @brief  Cài đặt Digital Low-Pass Filter (DLPF_CFG trong CONFIG).
 *         Giá trị thấp = băng thông rộng, giá trị cao = lọc mạnh hơn.
 */
typedef enum {
    MPU6050_DLPF_BW_260HZ = 0, /*!< Gyro BW 256Hz, Accel BW 260Hz */
    MPU6050_DLPF_BW_184HZ = 1, /*!< Gyro BW 188Hz, Accel BW 184Hz */
    MPU6050_DLPF_BW_094HZ = 2, /*!< Gyro BW  98Hz, Accel BW  94Hz */
    MPU6050_DLPF_BW_044HZ = 3, /*!< Gyro BW  42Hz, Accel BW  44Hz */
    MPU6050_DLPF_BW_021HZ = 4, /*!< Gyro BW  20Hz, Accel BW  21Hz */
    MPU6050_DLPF_BW_010HZ = 5, /*!< Gyro BW  10Hz, Accel BW  10Hz */
    MPU6050_DLPF_BW_005HZ = 6, /*!< Gyro BW   5Hz, Accel BW   5Hz */
} MPU6050_DLPF_t;

/* ============================================================================
 *  CẤU TRÚC DỮ LIỆU
 * ============================================================================ */

/**
 * @brief  Dữ liệu thô đọc trực tiếp từ thanh ghi (chưa qua chuyển đổi).
 */
typedef struct {
    int16_t accel_x;  /*!< Gia tốc trục X (LSB) */
    int16_t accel_y;  /*!< Gia tốc trục Y (LSB) */
    int16_t accel_z;  /*!< Gia tốc trục Z (LSB) */
    int16_t temp;     /*!< Nhiệt độ (LSB)        */
    int16_t gyro_x;   /*!< Góc quay trục X (LSB) */
    int16_t gyro_y;   /*!< Góc quay trục Y (LSB) */
    int16_t gyro_z;   /*!< Góc quay trục Z (LSB) */
} MPU6050_RawData_t;

/**
 * @brief  Dữ liệu đã chuyển đổi sang đơn vị vật lý.
 */
typedef struct {
    float accel_x;  /*!< Gia tốc trục X (g)      */
    float accel_y;  /*!< Gia tốc trục Y (g)      */
    float accel_z;  /*!< Gia tốc trục Z (g)      */
    float temp_c;   /*!< Nhiệt độ (°C)            */
    float gyro_x;   /*!< Tốc độ góc trục X (°/s) */
    float gyro_y;   /*!< Tốc độ góc trục Y (°/s) */
    float gyro_z;   /*!< Tốc độ góc trục Z (°/s) */
} MPU6050_ScaledData_t;

/**
 * @brief  Góc Euler được tính bởi Complementary Filter.
 */
typedef struct {
    float pitch;  /*!< Góc ngẩng đầu/cúi (°)   – trục X */
    float roll;   /*!< Góc nghiêng trái/phải (°) – trục Y */
} MPU6050_Angle_t;

/**
 * @brief  Handle chính của driver MPU6050.
 *         Khai báo một instance duy nhất trong ứng dụng.
 */
typedef struct {
    /* Cấu hình người dùng */
    MPU6050_GyroFS_t   gyro_fs;     /*!< Dải đo Gyroscope đã chọn       */
    MPU6050_AccelFS_t  accel_fs;    /*!< Dải đo Accelerometer đã chọn   */

    /* Hệ số nhạy (tự động tính sau init) */
    float gyro_sens;   /*!< LSB per °/s  (e.g. 65.5 ở ±500°/s) */
    float accel_sens;  /*!< LSB per g    (e.g. 8192 ở ±4g)     */

    /* Dữ liệu thô và đã chuyển đổi */
    MPU6050_RawData_t    raw;
    MPU6050_ScaledData_t scaled;

    /* Góc tính bởi Complementary Filter */
    MPU6050_Angle_t      angle;

    /* Hệ số alpha cho Complementary Filter (0.0 – 1.0)
       Giá trị mặc định: 0.96 (96% Gyro + 4% Accel) */
    float comp_filter_alpha;

    /* Thời điểm đọc lần cuối để tính dt (ms) */
    uint32_t last_tick;

    /* Cờ báo có dữ liệu mới từ ngắt DRDY */
    volatile uint8_t data_ready_flag;

    /* Trạng thái khởi tạo */
    uint8_t initialized;

} MPU6050_Handle_t;

/* ============================================================================
 *  PUBLIC API
 * ============================================================================ */

/**
 * @brief  Khởi tạo MPU6050.
 *         Kiểm tra WHO_AM_I, đánh thức chip, cấu hình gyro/accel range và DLPF.
 *         Bật ngắt Data-Ready ra chân PA15.
 *
 * @param  hdev     Con trỏ đến handle MPU6050 (khai báo trong ứng dụng).
 * @param  gyro_fs  Dải đo gyroscope (xem @ref MPU6050_GyroFS_t).
 * @param  accel_fs Dải đo accelerometer (xem @ref MPU6050_AccelFS_t).
 * @param  dlpf     Cài đặt DLPF (xem @ref MPU6050_DLPF_t).
 * @retval HAL_OK nếu thành công, HAL_ERROR nếu không nhận dạng được chip.
 */
HAL_StatusTypeDef MPU6050_Init(MPU6050_Handle_t *hdev,
                                MPU6050_GyroFS_t  gyro_fs,
                                MPU6050_AccelFS_t accel_fs,
                                MPU6050_DLPF_t    dlpf);

/**
 * @brief  Đọc tất cả dữ liệu thô (14 byte) từ thanh ghi 0x3B–0x48.
 *         Kết quả lưu vào hdev->raw.
 *
 * @param  hdev  Con trỏ đến handle MPU6050.
 * @retval HAL_OK nếu I2C thành công.
 */
HAL_StatusTypeDef MPU6050_ReadRaw(MPU6050_Handle_t *hdev);

/**
 * @brief  Chuyển đổi dữ liệu thô sang đơn vị vật lý (g, °/s, °C).
 *         Kết quả lưu vào hdev->scaled.
 *         Cần gọi MPU6050_ReadRaw() trước.
 *
 * @param  hdev  Con trỏ đến handle MPU6050.
 */
void MPU6050_ConvertScaled(MPU6050_Handle_t *hdev);

/**
 * @brief  Tính góc Pitch và Roll bằng Complementary Filter.
 *         Kết quả lưu vào hdev->angle.
 *         Cần gọi MPU6050_ConvertScaled() trước.
 *
 *         angle = alpha * (angle + gyro * dt) + (1-alpha) * accel_angle
 *         dt được tính tự động từ HAL_GetTick().
 *
 * @param  hdev  Con trỏ đến handle MPU6050.
 */
void MPU6050_UpdateAngle(MPU6050_Handle_t *hdev);

/**
 * @brief  Hàm tiện ích: đọc raw → convert → update angle trong một lệnh.
 *         Dùng trong main loop hoặc timer callback.
 *
 * @param  hdev  Con trỏ đến handle MPU6050.
 * @retval HAL_OK nếu I2C thành công.
 */
HAL_StatusTypeDef MPU6050_Update(MPU6050_Handle_t *hdev);

/**
 * @brief  Callback ngắt Data-Ready. Gọi trong HAL_GPIO_EXTI_Callback() khi
 *         GPIO_Pin == MPU6050_INT_PIN.
 *
 *         Đặt cờ hdev->data_ready_flag = 1 để main loop biết có dữ liệu mới.
 *
 * @param  hdev  Con trỏ đến handle MPU6050.
 */
void MPU6050_DRDY_Callback(MPU6050_Handle_t *hdev);

/**
 * @brief  Kiểm tra và xóa cờ Data-Ready.
 *
 * @param  hdev  Con trỏ đến handle MPU6050.
 * @retval 1 nếu có dữ liệu mới, 0 nếu chưa.
 */
uint8_t MPU6050_IsDataReady(MPU6050_Handle_t *hdev);

/**
 * @brief  Đọc nhiệt độ chip (°C).
 *
 * @param  hdev  Con trỏ đến handle MPU6050.
 * @retval Nhiệt độ tính bằng float (°C).
 */
float MPU6050_GetTemperature(MPU6050_Handle_t *hdev);

/**
 * @brief  Reset Software – ghi bit DEVICE_RESET vào PWR_MGMT_1.
 *         Sau khi reset, cần gọi lại MPU6050_Init().
 *
 * @param  hdev  Con trỏ đến handle MPU6050.
 * @retval HAL_OK nếu thành công.
 */
HAL_StatusTypeDef MPU6050_Reset(MPU6050_Handle_t *hdev);

#ifdef __cplusplus
}
#endif

#endif /* __MPU6050_H__ */
